apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{- include "helm-chart.labels" . | nindent 4 }}
  name: {{ .Values.service.name | quote }}
spec:
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}